version: "3.7"
services:
    web: 
        image: ranur/codeigniter:3.11-sessions
        volumes:
            - ./setup:/app
        ports:
            - 81:8000
        depends_on:
            - mariadb
        container_name: dasboard
    mariadb:
        image: ranur/mariadb:10.3-mudo
        volumes:
            - ./db_sqldata/db_gn.sql:/docker-entrypoint-initdb.d/dump.sql
        ports:
            - 3306:3306
        container_name: mariaDB
    phpmyadmin:
        image: ranur/phpmyadmin:1.1-links
        ports:
            - 85:80
        container_name: phpmyadmin
        